### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Cphoward484** [SCCapstone/capstone22#112]
Hello Dr. @josemvidal 

I noticed on Dropbox, under the https://capstone.cse.sc.edu/milestone/testing/ there is a Final Deadline requirement, this may be a ridiculous question but there was no outline for when this segment is due? Is this for our current capstone or the next upcoming capstone? Please let me know, thank you!

Best,
Allen H.

**Comment by Cphoward484** [comment]
Or is the deadline implying the 25th of this month?

**Comment by josemvidal** [comment]
<img width="662" alt="image" src="https://user-images.githubusercontent.com/228704/164991503-8d3aef3c-18be-4599-a6eb-f2810b0ae14e.png">

what is due then? [this](https://capstone.cse.sc.edu/milestone/testing/#deliverables):

<img width="742" alt="image" src="https://user-images.githubusercontent.com/228704/164991512-76589ca1-9385-42e8-a8d8-ace0e4bf089d.png">

**Comment by Cphoward484** [comment]
Thank you, I completely missed that hahah!
