### ISSUE TITLE
Testing Video 

### ISSUE THREAD

**Issue by Cphoward484** [SCCapstone/capstone22#113]
Unit Test:

https://user-images.githubusercontent.com/55643633/165196548-4244fbc8-ce18-419f-9772-1e62881bba5c.mp4

**Comment by Cphoward484** [comment]
@josemvidal Hi Dr. Vidal, 

Sorry for the late message, but I was not sure if I was meant to tag the TA or yourself for this issue. It has been a wild semester, and I make mistakes sometimes. Please let me know, thank you!

best, 
Allen

**Comment by josemvidal** [comment]
we got it.
